### ISSUE TITLE
May I include it in CustomPiOS List of Distributions?

### ISSUE THREAD

**Issue by guysoft** [myoung34/tilty-pi#6]
Hey,
I am the creator of CustomPiOS and came across the distro.
If its being maintained, would love to add it to this section in the readme:
https://github.com/guysoft/CustomPiOS#list-of-distributions-using-custompios

If you like you can also PR it yourself.

**Comment by myoung34** [comment]
Sure. I submitted a PR here: https://github.com/guysoft/CustomPiOS/pull/95

But I dont know much about RST so the formatting could be off

**Comment by guysoft** [comment]
You got it right :)
